name: svm
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - rise

# Setup RISE (https://github.com/damianavila/RISE) slideshows:
# $ jupyter nbextension install rise --py --sys-prefix
# $ jupyter nbextension enable rise --py --sys-prefix
