name: svm
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - mlxtend
  - seaborn
  - pip
  - pip:
    - rise
